<h3><center>arrays</center></h3>

In [36]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [4]:
x.shape

(2, 3)

In [6]:
x.dtype

dtype('int32')

In [7]:
x[0, 1]

2

In [37]:
x[:, 0]

array([1, 4], dtype=int32)

<h3><center>inserting</center></h3>

In [13]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x = np.append(x, [7, 8, 9])
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x = np.append(arr=x, values=[[7, 8, 9]], axis=0)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x = np.add(x, x)
x

array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)

In [26]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [30]:
x = np.array([[1, 2, 3], [4, 5, 6]])
np.reshape(x, (-1, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [32]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
x.transpose()

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x.flatten()

array([1, 2, 3, 4, 5, 6])

In [39]:
a = [4, 3, 5, 7, 6, 8]
np.take(a, [[0, 1], [2, 3]])

array([[4, 3],
       [5, 7]])

In [41]:
a = np.arange(5)
np.put(a, [0, 2], [-44, -55])
a

array([-44,   1, -55,   3,   4])

In [44]:
a = np.arange(5)
np.put(a, [0, 2], 10)
a

array([10,  1, 10,  3,  4])

In [50]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x.max())
print(x.max(axis=0))
print(x.max(axis=1))

6
[4 5 6]
[3 6]


In [51]:
x = np.array([[0.12541, 0.753682, 0.3453453], [0.45261364, 0.8957225, 0.3842736]])
np.round(x, 3)

array([[0.125, 0.754, 0.345],
       [0.453, 0.896, 0.384]])

In [53]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(x))
print(np.sum(x, axis=1))

21
[ 6 15]


In [55]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(np.mean(x))
print(np.mean(x, axis=0))

3.5
[2.5 3.5 4.5]


In [56]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(np.std(x))
print(np.std(x, axis=0))

1.707825127659933
[1.5 1.5 1.5]


In [66]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x + 1)
print(x * 2)
print(x / 2)
print('floor', x // 2)
print('mod', x % 2)
print('power', pow(x, 2))

[[2 3 4]
 [5 6 7]]
[[ 2  4  6]
 [ 8 10 12]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
floor [[0 1 1]
 [2 2 3]]
mod [[1 0 1]
 [0 1 0]]
power [[ 1  4  9]
 [16 25 36]]


In [68]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x *= 2
x **= 2
x

array([[  4,  16,  36],
       [ 64, 100, 144]])